### ISSUE TITLE
"b" and "strong" are not properly weighted

### ISSUE THREAD

**Issue by klemola** [scottcorgan/elm-css-normalize#3]
Hi!

I noticed that `Normalize.elm` is missing a declaration that is present in `normalize.css`.

```css
/**
 * Prevent the duplicate application of `bolder` by the next rule in Safari 6.
 */

b,
strong {
  font-weight: inherit;
}

/**
 * Add the correct font weight in Chrome, Edge, and Safari.
 */

b,
strong {
  font-weight: bolder;
}

```

First declaration with `inherit` weight is properly implemented, but the latter (`bolder`) is missing. The result is (not suprisingly) that `b` and `strong` do not visually modify normal copy text at all.

Here's the declarations:

[Normalize.elm#L131](https://github.com/scottcorgan/elm-css-normalize/blob/master/src/Css/Normalize.elm#L131)

[normalize.css#L135](https://github.com/necolas/normalize.css/blob/master/normalize.css#L135)
